### ISSUE TITLE
Enhancement request? Merge objects in lists by default

### ISSUE THREAD

**Issue by raptortalons** [avian2/jsonmerge#17]
I would like to use this library but the default behavior of override for lists isn't appropriate for me. I'd expect if items in a list are objects than they be merged as well. The merge strategy solution seems like overkill for this case. It seems that generally this is a more reasonable behavior than the current default. Any chance the default behavior will be changed?

**Comment by avian2** [comment]
I don't understand. What kind of default merge strategy do you propose for lists?

**Comment by raptortalons** [comment]
Not sure what to call it - but I'd say object merge for lists. By this I mean each item in two lists being merged would be merged. If the base value is not an object (or even another list for that matter) then it will simply be overwritten by the head. Otherwise it will be merged normally.

**Comment by avian2** [comment]
I think it is dangerous to assume by default that HEAD and BASE lists are ordered. What happens if two lists are not of the same size? How do you know which item was added? Was a new item added at the start or the end of the list? Or somewhere in the middle (if lists are ordered by some unknown key) This is why I think the least surprising default behaviour for lists is for HEAD to overwrite BASE.

You can always define your own strategy if your lists obey some special rules regarding their elements.

**Comment by raptortalons** [comment]
OK, good point.
