### ISSUE TITLE
Upgrade to latest jsonschema

### ISSUE THREAD

**Issue by terrisgit** [avian2/jsonmerge#34]
jsonschema is currently on 3.0.0a1. jsonmerge uses 2.6.0

**Comment by avian2** [comment]
I've added a requirement for jsonschema<3.0.0 to `setup.py` for now. It seems some tests related to references fail with 3.0.0, but otherwise it seems jsonmerge largely works as-is with 3.0.0.

Actually, I'm not sure what is the status of 3.0.0a1 on pypi. For me `pip install jsonschema` still installs 2.6.0 by default.

**Comment by terrisgit** [comment]
Got it. There’s no jsonschema release between 2.6.0 and 3.0.0 .. not sure what is in 3.0 - I’m working fine with 2.6 and hopefully i wont use a library that needs jsonschema 3 but It’s probably going to happen in the next 6 months

**Comment by terrisgit** [comment]
schema 3.0.0 is not on pypi.
